<?php

return [

    'page_title' => 'Cookie policy',
    'page_description' => 'Read about cookie policy',
    'sub_title' => 'Cookie policy',
    'paragraph_1' => 'Cookie is a small piece of data that is stored on your computer or mobile device when you visit a website.  When we use cookies, we may use “session” cookies (that last until you close your browser) or “persistent” cookies (that last until they expire or are deleted by you or by browser).',
    'paragraph_2' => 'If you want to see what cookies we store about you while browsing our website, you can use <a href="https://chrome.google.com/webstore/detail/editthiscookie/fngmhnnpilhplaeedifhccceomclgfbg?hl=en-US"><u>Edit this Cookie</u></a> extension for Google Chrome, which will provide you with a complete list. Might you have some question about a specific cookie, you are more than welcome to contact us at info@agimo.dk.',
    'paragraph_3' => 'Technical cookies are needed for the website to work properly. Our website is coded in Laravel, which makes it easy to protect us from cross-site request forgery (CSRF) attacks. Cross-site request forgeries are a type of malicious exploit whereby unauthorized commands are performed on behalf of an authenticated user. Laravel automatically generates a CSRF "token" for each active user session managed by the application. This token is used to verify that the authenticated user is the one actually making the requests to the application. Laravel stores the current CSRF token in a XSRF-TOKEN cookie that is included with each response generated by the framework. You can use the cookie value to set the X-XSRF-TOKEN request header. This cookie is primarily sent as a convenience since some JavaScript frameworks and libraries, like Angular and Axios, automatically place its value in the X-XSRF-TOKEN header.
                        All the session information is stored in our second cookie called agimo_session. These are both autogenarated by Laravel, not by us. Read more about Laravel´s technical cookies <a href="https://laravel.com/docs/5.7/session"><u>here</u></a>.',
    'paragraph_4' => 'Functional cookies allow a website to remember information that changes the way the website looks or behaves. Eg. your preferred language.',
    'paragraph_5' => 'Statistical cookies help us to understand how visitors interact with websites by collecting and reporting information. We use this information to analyse and understand trends, to administer the site, to learn about user behaviour on the site, to improve the quality and effectiveness of our content, features and our services, and to gather demographic information about our user base as a whole. We may use this information in our marketing and advertising services.',
    'paragraph_6' => 'To collect statistical data, we use two provider - Google Analytics and Hotjar. If you wish to refuse these cookies, please follow their instructions - <a href="https://tools.google.com/dlpage/gaoptout"><u>Google Analytics</u></a> and <a href="https://www.hotjar.com/legal/compliance/opt-out"><u>Hotjar</u></a>.',
    'paragraph_7' => 'The information we collect',
    'paragraph_8' => 'Cookie in no way gives us access to your computer or provides us personal information about you, such as your name, address or e-mail address. By using Google Analytics and Hotjar, several data about you are being collected such as:',
    'paragraph_9' => 'Web pages and content you view and links you click on while navigating within our website',
    'paragraph_10' => 'Information about your interactions with our content',
    'paragraph_11' => 'Information about your interactions with our email messages, such as the links you click on and whether you open or forward a message, the date and time of these interactions and the device you use to read emails',
    'paragraph_12' => 'Your Internet Protocol (IP) address (a numerical address assigned to your device by your Internet service provider so that other devices connected to the Internet can communicate with you online) that can sometimes be used to derive your general geographic area',
    'paragraph_13' => 'Your device type, screen size, browser type, language and other settings, memory capacity, plug-ins, Internet domain, TCP configuration parameters, operating system, time zone and the names, versions and package IDs of software installed on your device',
    'paragraph_14' => 'Standard server log information',
    'paragraph_15' => 'Controlling cookies',
    'paragraph_16' => 'You can choose to accept or reject cookies. Once you accept cookies, you can always delete and block them in the settings of your web browser. You can find a <a href="http://minecookies.org/cookiehandtering/"><u>guide here</u></a>, depending on which internet browser you are using.',
    'paragraph_17' => 'We may change this notice from time to time by updating this page. You should, therefore, occasionally access this page to make sure you are happy with any changes.',
    'paragraph_18' => 'If you have questions about using cookies on www.agimo.dk, please feel free to contact us.'

];
